### ISSUE TITLE
(Extra) As a user, when I hover over the tile, I want to see a hover effect

### ISSUE THREAD

**Issue by dattupatel** [Shivani2224/Tic-Tac-Toe#6]
One or all of the following:
- Grow size
- Colour change
- Shadow effect

Example for grow: https://www.w3schools.com/howto/howto_css_zoom_hover.asp

![CPT2405302244-1220x870](https://github.com/Shivani2224/Tic-Tac-Toe/assets/6920655/e05b4aa3-ad7f-4ded-a60c-757917e4c93c)

Advanced: You can also show a faded `X` or `0` in that tile when you hover.

**Comment by Shivani2224** [comment]
Advanced: You can also show a faded X or 0 in that tile when you hover.

I don't know how to do this.

**Comment by dattupatel** [comment]
Look at the following code for
- `mouseover`
- `mouseout`
- `.box` styles


```javascript
let boxes = document.querySelectorAll(".box");
let resetbtn = document.querySelector("#reset");
let turn = document.querySelector("#playerName");
let turnO = true;
let playerWinner = true;
let count = 0;
let winningPatten = [
  [0, 1, 2],
  [0, 3, 6],
  [0, 4, 8],
  [1, 4, 7],
  [2, 5, 8],
  [2, 4, 6],
  [3, 4, 5],
  [6, 7, 8],
];

boxes.forEach((box) => {
  box.addEventListener("mouseover", () => {
    if (!box.disabled) {
      box.innerText = turnO ? "X" : "O";
    }
  });
  box.addEventListener("mouseout", () => {
    if (!box.disabled) {
      box.innerText = "";
    }
  });

  box.addEventListener("click", () => {
    if (turnO === true) {
      box.innerText = "X";
      turnO = false;
      playerName.innerText = " Player 2 Turn";
    } else if (turnO === false) {
      box.innerText = "O";
      turnO = true;
      playerName.innerText = " Player 1 Turn";
    }
    box.disabled = true;
    checkWinner();

    count++;
    if (count === 9 && !checkWinner()) {
      console.log("no winner");
      playerName.innerText = "Match Draw";
      disableBtn();
    }
  });
});

// const drawHandler = () => {

//   }
// };
function disableBtn() {
  for (let box of boxes) {
    box.disabled = true;
  }
}

const enableBtn = () => {
  for (let box of boxes) {
    box.disabled = false;
    box.innerText = "";
    box.style.color = "";
    playerName.innerText = " Player 1 Turn";
  }
  count = 0;
};

const checkWinner = () => {
  for (let pattern of winningPatten) {
    let pos1Val = boxes[pattern[0]].innerText;
    let pos2Val = boxes[pattern[1]].innerText;
    let pos3Val = boxes[pattern[2]].innerText;

    if (pos1Val != "" && pos2Val != "" && pos3Val != "") {
      if (pos1Val === pos2Val && pos2Val === pos3Val) {
        playerName.innerText = "winner is " + pos1Val;

        boxes[pattern[0]].style.color = "red";
        boxes[pattern[1]].style.color = "red";
        boxes[pattern[2]].style.color = "red";
        disableBtn();
        return true;
      }
    }
  }
};

const resetGame = () => {
  turnO = true;
  enableBtn();
};

resetbtn.addEventListener("click", resetGame);
```

```css
* {
  margin: 0;
  padding: 0;
}
body {
  background-color: #ff9fb2;
  text-align: center;
}
.container {
  height: 70vh;
  display: flex;

  align-items: center;
  justify-content: center;
}

.game {
  height: 60vmin;
  width: 60vmin;
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  gap: 1.5vmin;
}

.box {
  height: 18vmin;
  width: 18vmin;
  border-radius: 1rem;
  box-shadow: 0 0 1rem rgba(0, 0, 0, 0.5);
  font-size: 8vmin;
  color: #60ab9a;
  border: none;
  transform 0.2s ease-out;
}
.box:hover:not(:disabled) {
  cursor: pointer;
  transform: scale(1.1);
  color: rgba(0, 0, 0, 0.1);
}

#reset {
  padding: 1vmin;
  font-size: 3vmin;
  background-color: #000000;
  border-radius: 1rem;
  color: white;
  height: 5%;
  width: 20vmin;
}
#playerName {
  margin-top: 1vmin;
  padding: 2vmin;
  font-size: 3vmin;
  background-color: #000000;
  box-shadow: 0 0 1rem rgba(0, 0, 0, 0.8);
  border-radius: 1rem;
  color: white;
  height: 5%;
  width: 25vmin;
  text-align: center;
}
h1 {
  margin: 1vmin;
}

#reset:hover {
  cursor: pointer;
  background-color: white;
  color: #000000;
  box-shadow: 0 0 2rem rgba(0, 0, 0, 1);
  transform: scale(1.2);
}
```

Above 
![CPT2406021313-1792x870](https://github.com/Shivani2224/Tic-Tac-Toe/assets/6920655/6e593ffd-6155-4a10-b98b-cdbdaf6fe2f2)
